import "dotenv/config";
import { Transaction, } from "@mysten/sui/transactions";
import {
	handleError,
	initializeContext,
	requireEnv,
} from "../../../ts-scripts/utils/helper";
import { writeFileSync } from 'node:fs';
import { delay, getDelayMs } from "../../../ts-scripts/utils/delay";
import { findCreatedObjectIdByTypeSuffix, SuiObjectChange, requireObjectChanges } from "../../../ts-scripts/utils/tx-parsing";
import { execSync } from 'child_process';

function findPublishedPackageId(objectChanges: SuiObjectChange[]): string {
	const published = objectChanges.find(
		(change): change is Extract<SuiObjectChange, { type: 'published' }> =>
			change.type === 'published',
	);

	if (!published) {
		throw new Error('Could not find published package ID in objectChanges');
	}

	return published.packageId;
}

function writeConstantsFile(args: {
	originalAt: string;
	publishedAt: string;
	newCapId: string;
	frontierTransitAuthorityId: string;
}): void {
	const { originalAt, publishedAt, newCapId, frontierTransitAuthorityId } = args;

	const contents = `// AUTO-GENERATED FILE.
// Generated by publish.ts
// Do not edit manually.

export const FTA_ORIGINAL_AT = '${originalAt}';
export const FTA_PUBLISHED_AT = '${publishedAt}';
export const FTA_UPGRADE_CAP_ID = '${newCapId}';
export const FTA_OBJECT_ID = '${frontierTransitAuthorityId}';
`;
	writeFileSync("dapps/fta/libs/auto-constants.ts", contents, 'utf8');
}


async function publish(
	ctx: ReturnType<typeof initializeContext>,
) {
	const { client, keypair, config, address } = ctx;

	const { modules, dependencies } = JSON.parse(
		execSync(`sui move build --dump-bytecode-as-base64 --path contracts/fta`, {
			encoding: 'utf-8',
		})
	);

	let publishTx = new Transaction();
	const upgradeCap = publishTx.publish({ modules, dependencies });
	publishTx.transferObjects([upgradeCap], address);

	const publishExec = await client.signAndExecuteTransaction({
		signer: keypair,
		transaction: publishTx,
		options: { showObjectChanges: true, showEffects: true, showEvents: true },
	});

	await delay(getDelayMs());

	//const publishDigest = "21sYKCJ4wsZVG81BXRkTbdnorcbmJGWUmtcMUxN938Xv";
	const publishDigest = publishExec.digest;
	console.log("Published digest: ", publishDigest);

	const publishBlock = await client.getTransactionBlock({
		digest: publishDigest,
		options: {
			showEffects: true,
			showObjectChanges: true,
			showInput: false,
			showEvents: false,
			showBalanceChanges: false,
		},
	});
	const objectChanges = requireObjectChanges(publishBlock.objectChanges);
	const publishedPackageId = findPublishedPackageId(objectChanges);

	const upgradeCapId = findCreatedObjectIdByTypeSuffix(
		objectChanges,
		'::package::UpgradeCap',
	);
	const frontierTransitAuthorityId = findCreatedObjectIdByTypeSuffix(
		objectChanges,
		'::fta::FrontierTransitAuthority',
	);

	console.log('Publish complete');
	console.log('  digest:      ', publishDigest);
	console.log('  packageId:   ', publishedPackageId);
	console.log('  upgradeCapId:', upgradeCapId);
	console.log('  ftaId:       ', frontierTransitAuthorityId);


	// const transferTx = new Transaction();

	// transferTx.moveCall({
	// 	target: `${publishedPackageId}::fta::exchange_upgrade_cap`,
	// 	arguments: [
	// 		transferTx.object(frontierTransitAuthorityId),
	// 		transferTx.object(upgradeCapId),
	// 	],
	// });

	// const transferExec = await client.signAndExecuteTransaction({
	// 	signer: keypair,
	// 	transaction: transferTx,
	// 	options: { showObjectChanges: true, showEffects: true, showEvents: true },
	// });
	// console.log("Transfer exec digest: ", transferExec.digest);
	// console.log("Transfer exec changes:\n", transferExec.objectChanges);

	// const createdCapChange = transferExec.objectChanges?.findLast(change => {
	// 	return change.type === 'created' && change.objectType.endsWith('::upgrade_cap::UpgradeCap')
	// });
	// if (!createdCapChange || createdCapChange.type !== 'created') {
	// 	throw new Error('No UpgradeCap created in transaction');
	// }
	//const newCapId = createdCapChange!.objectId;
	const newCapId = upgradeCapId;

	console.log('exchange_upgrade_cap complete');
	// console.log('  digest:', transferExec.digest);

	writeConstantsFile({
		originalAt: publishedPackageId,
		publishedAt: publishedPackageId,
		newCapId: newCapId,
		frontierTransitAuthorityId,
	});
	console.log("Constants file written");
}

async function main() {
	try {
		const playerKey = requireEnv("UTOPIA_PRIVATE_KEY");
		const playerCtx = initializeContext("testnet", playerKey);
		await publish(playerCtx);
	} catch (error) {
		handleError(error);
	}
}

main();