// AUTO-GENERATED FILE.
// Generated by publish.ts
// Do not edit manually.

export const FTA_ORIGINAL_AT = '0x4d22d8e0cdc3fe27249f1f7ffb8a0b721ea32c80d33817e9fe394de07c771965';
export const FTA_PUBLISHED_AT = '0x4d22d8e0cdc3fe27249f1f7ffb8a0b721ea32c80d33817e9fe394de07c771965';
export const FTA_UPGRADE_CAP_ID = '0xc7a8f01d4b25dc820ec85d96961d473939ad1cb57a4da2c7656629e5ffd15de3';
export const FTA_OBJECT_ID = '0x9f68faee73d9817cbf96ea86a0674465731e79da647466a5fe38242816225fc4';
