// AUTO-GENERATED FILE.
// Generated by publish.ts
// Do not edit manually.

export const FTA_ORIGINAL_AT = '2B5STcVfN8ntHcBMX28FzDkkm7wTMRp4gQd1wgq8kXnR';
export const FTA_PUBLISHED_AT = '0x8862a284f27ded113ab3f70b1450e2edf2ee884177728ad290d68188b88ea512';
export const FTA_UPGRADE_CAP_ID = '0x6102276a0f4b3c0186ea20ea7b5f96705dea7a934c155393a9d1d96538f7a82f';
export const FTA_OBJECT_ID = '0x366d65424d02204f82e96cdb7017c9309226da2206dfd52698b4de087cc6f3fd';
