// AUTO-GENERATED FILE.
// Generated by publish.ts
// Do not edit manually.

export const FTA_ORIGINAL_AT = '4ZsbyMmSyS4jfaqs1bRG7Hop58r9GncYNvGa64SNHVJY';
export const FTA_PUBLISHED_AT = '0xa41b9562dcd3380f51a8b0f1343bf9202e5fdcc91413b1fef78b70e7601ec0f6';
export const FTA_OBJECT_ID = '0x4d26afefa2475de77d23f1238efdd2c795b641e59dd16621873d845c19419ce4';
