import "dotenv/config";
import { Transaction, } from "@mysten/sui/transactions";
import { SuiJsonRpcClient } from "@mysten/sui/jsonRpc";
import {
	handleError,
	initializeContext,
	requireEnv,
} from "../../../ts-scripts/utils/helper";
import { createClient } from "../../../ts-scripts/utils/client";
import { execSync } from 'child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const tmpclient = createClient("testnet");
type GetTxBlockResult = Awaited<ReturnType<typeof tmpclient.getTransactionBlock>>;
type SuiObjectChange = NonNullable<GetTxBlockResult['objectChanges']>[number];

function requireObjectChanges(
	objectChanges: SuiObjectChange[] | undefined | null,
): SuiObjectChange[] {
	if (!objectChanges?.length) {
		throw new Error('No objectChanges found on transaction result');
	}
	return objectChanges;
}

function findPublishedPackageId(objectChanges: SuiObjectChange[]): string {
	const published = objectChanges.find(
		(change): change is Extract<SuiObjectChange, { type: 'published' }> =>
			change.type === 'published',
	);

	if (!published) {
		throw new Error('Could not find published package ID in objectChanges');
	}

	return published.packageId;
}

function findCreatedObjectIdByTypeSuffix(
	objectChanges: SuiObjectChange[],
	typeSuffix: string,
): string {
	const matches = objectChanges.filter(
		(change): change is Extract<SuiObjectChange, { type: 'created' }> =>
			change.type === 'created' &&
			typeof change.objectType === 'string' &&
			change.objectType.endsWith(typeSuffix),
	);

	if (matches.length === 0) {
		throw new Error(
			`Could not find a created object with type ending in "${typeSuffix}"`,
		);
	}

	if (matches.length > 1) {
		throw new Error(
			`Found multiple created objects with type ending in "${typeSuffix}"; refine the selector`,
		);
	}

	return matches[0].objectId;
}

function writeConstantsFile(args: {
	originalAt: string;
	publishedAt: string;
	frontierTransitAuthorityId: string;
}): void {
	const { originalAt, publishedAt, frontierTransitAuthorityId } = args;

	const contents = `// AUTO-GENERATED FILE.
// Generated by publish.ts
// Do not edit manually.

export const FTA_ORIGINAL_AT = '${originalAt}';
export const FTA_PUBLISHED_AT = '${publishedAt}';
export const FTA_OBJECT_ID = '${frontierTransitAuthorityId}';
`;
	writeFileSync("dapps/fta/libs/auto-constants.ts", contents, 'utf8');
}


async function publish(
	ctx: ReturnType<typeof initializeContext>,
) {
	const { client, keypair, config, address } = ctx;

	const { modules, dependencies } = JSON.parse(
		execSync(`sui move build --dump-bytecode-as-base64 --path sui/fta`, {
			encoding: 'utf-8',
		})
	);

	let publishTx = new Transaction();
	const upgradeCap = publishTx.publish({ modules, dependencies });
	publishTx.transferObjects([upgradeCap], address);

	const publishExec = await client.signAndExecuteTransaction({
		signer: keypair,
		transaction: publishTx,
	});

	const publishDigest = "4ZsbyMmSyS4jfaqs1bRG7Hop58r9GncYNvGa64SNHVJY"; //publishExec.digest;
	console.log("Published digest: ", publishDigest);

	const publishBlock = await client.getTransactionBlock({
		digest: publishDigest,
		options: {
			showEffects: true,
			showObjectChanges: true,
			showInput: false,
			showEvents: false,
			showBalanceChanges: false,
		},
	});
	const objectChanges = requireObjectChanges(publishBlock.objectChanges);
	const publishedPackageId = findPublishedPackageId(objectChanges);

	const upgradeCapId = findCreatedObjectIdByTypeSuffix(
		objectChanges,
		'::package::UpgradeCap',
	);
	const frontierTransitAuthorityId = findCreatedObjectIdByTypeSuffix(
		objectChanges,
		'::fta::FrontierTransitAuthority',
	);

	console.log('Publish complete');
	console.log('  digest:      ', publishDigest);
	console.log('  packageId:   ', publishedPackageId);
	console.log('  upgradeCapId:', upgradeCapId);
	console.log('  ftaId:       ', frontierTransitAuthorityId);

	const transferTx = new Transaction();

	const [customUpgradeCap] = transferTx.moveCall({
		target: `${publishedPackageId}::fta::exchange_upgrade_cap`,
		arguments: [
			transferTx.object(frontierTransitAuthorityId),
			transferTx.object(upgradeCapId),
		],
	});
	transferTx.transferObjects([customUpgradeCap], address);

	const transferExec = await client.signAndExecuteTransaction({
		signer: keypair,
		transaction: transferTx,
	});

	console.log('exchange_upgrade_cap complete');
	console.log('  digest:', transferExec.digest);

	writeConstantsFile({
		originalAt: publishDigest,
		publishedAt: publishedPackageId,
		frontierTransitAuthorityId,
	});
	console.log("Constants file written");
}

async function main() {
	try {
		const playerKey = requireEnv("UTOPIA_PRIVATE_KEY");
		const playerCtx = initializeContext("testnet", playerKey);
		await publish(playerCtx);
	} catch (error) {
		handleError(error);
	}
}

main();